# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: HOK Revit Addins Build

on:
  push:
    branches: [ "TEST" ]

env:
  solution-path: '**/HOK.!(Core|MissionControl|Feedback|ParameterTools|FileOpeningMonitor|ModelReporting|SheetManager).sln'
  core-solution: '**/HOK.Core.sln'
  mc-solution: '**/HOK.MissionControl.sln'
  param-tool-solution: '**/HOK.ParameterTools.sln'
  feedback-solution: '**/HOK.Feedback.sln'
  sheet-manager-solution: '**/HOK.SheetManager.sln'
  build-platform: 'x64'
  revit-years: '["2019","2020","2021","2022","2023","2024","2025"]'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
